version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "./frontend/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
    groups:
      npm-dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      npm-dependencies:
        dependency-type: "production"
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
    groups:
      repo-nuget-dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      repo-nuget-dependencies:
        dependency-type: "production"
        patterns:
          - "*"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "./backend/" # Location of package manifests
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
    groups:
      nuget-dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      nuget-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
