# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET Web App

on:
  pull_request:
    branches:
      - "**"

jobs:
  build_test:
    runs-on: ubuntu-latest

    env:
      FIRESTORE_EMULATOR_HOST: ${{ vars.FIRESTORE_EMULATOR_HOST }}
      FIRESTORE_EMULATOR_PROJECT_ID: ${{ secrets.FIRESTORE_EMULATOR_PROJECT_ID }}

    strategy:
      matrix:
        dotnet-version: ["8.0.x"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          install_components: "cloud-firestore-emulator"

      - name: Install dependencies
        working-directory: ./backend/src/
        run: dotnet restore PruneUrl.Backend.sln

      - name: Build
        working-directory: ./backend/src/
        run: dotnet build --configuration Release --no-restore PruneUrl.Backend.sln

      - name: Run tests
        working-directory: ./backend/src/
        run: |
          gcloud emulators firestore start --quiet --host-port=${{ env.FIRESTORE_EMULATOR_HOST }} &
          sleep 5s
          dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ../coverage PruneUrl.Backend.sln

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: backend/coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "50 70"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && (success() || failure())
        with:
          recreate: true
          path: code-coverage-results.md
