name: Bump App Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump_git_tag_version:
    runs-on: "ubuntu-latest"

    outputs:
      version: ${{ steps.version.outputs.new_version }}
      changelog: ${{ steps.version.outputs.changelog }}

    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
  bump_react_app_version:
    runs-on: ubuntu-latest
    needs: bump_git_tag_version

    steps:
      - uses: actions/checkout@v3
      - name: Bump package.json version
        run: npm version ${{ needs.bump_git_tag_version.outputs.version }}
      - name: Commit package.json
        run: |
          git config --global user.name '${{ github.event.pusher.name }}'
          git config --global user.email '${{ github.event.pusher.email }}'
          git commit -m "chore: bump package.json version to ${{ needs.bump_git_tag_version.outputs.version }}"
          git push
  update_changelog:
    runs-on: ubunut-latest
    needs: bump_git_tag_version

    steps:
      - uses: actions/checkout@v3
      - name: Update CHANGELOG.md
        run: |
          echo "${{ needs.bump_git_tag_version.outputs.changelog }}" >> CHANGELOG.md
      - name: Commit CHANGELOG.md
        run: |
          git config --global user.name '${{ github.event.pusher.name }}'
          git config --global user.email '${{ github.event.pusher.email }}'
          git commit -m "documentation: Update CHANGELOG.md for version ${{ needs.bump_git_tag_version.outputs.version }}"
          git push
