name: Bump App Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  calculate_version:
    runs-on: "ubuntu-latest"

    outputs:
      version: ${{ steps.version.outputs.new_version }}
      changelog: ${{ steps.version.outputs.changelog }}

    steps:
      - uses: actions/checkout@v4
      - name: Calculate SemVer and Generate CHANGELOG Entry
        id: version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          dry_run: true

  bump_app_version_and_update_change_log:
    runs-on: ubuntu-latest
    needs: calculate_version

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup git config
        run: |
          git config --global user.name '${{ github.event.pusher.name }}'
          git config --global user.email '${{ github.event.pusher.email }}'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Bump package.json version
        working-directory: ./frontend/
        run: |
          npm config set git-tag-version false
          npm version ${{ needs.calculate_version.outputs.version }}

      - name: Commit package.json
        run: |
          git add :/
          git commit -m "chore(package): bump frontend package.json version to ${{ needs.calculate_version.outputs.version }}"

      - name: Update CHANGELOG.md
        run: |
          changelog="${{ needs.calculate_version.outputs.changelog }}"
          echo "${changelog:1}" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md

      - name: Commit CHANGELOG.md
        run: |
          git add :/
          git commit -m "chore(changelog): update CHANGELOG.md for version ${{ needs.calculate_version.outputs.version }}"

      - name: Push changes
        run: git push

  create_tag:
    runs-on: ubuntu-latest
    needs: [calculate_version, bump_app_version_and_update_change_log]

    steps:
      - uses: actions/checkout@v4
      - name: Tag latest commit
        run: |
          git pull
          git tag v${{ needs.calculate_version.outputs.version }}
          git push origin v${{ needs.calculate_version.outputs.version }}
